// Runtime env helper. Keeps references typed without z-env dependency.
export const env = {
  DATABASE_URL: process.env.DATABASE_URL ?? "",
  DIRECT_URL: process.env.DIRECT_URL ?? "",
  AUTH_SECRET: process.env.AUTH_SECRET ?? "dev-secret-change-me",
  AUTH_URL: process.env.AUTH_URL ?? "http://localhost:3000",
  AUTH_GOOGLE_ID: process.env.AUTH_GOOGLE_ID ?? "",
  AUTH_GOOGLE_SECRET: process.env.AUTH_GOOGLE_SECRET ?? "",
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL ?? "",
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "",
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY ?? "",
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET ?? "",
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY ?? "",
  STRIPE_PLATFORM_FEE_BPS: Number(process.env.STRIPE_PLATFORM_FEE_BPS ?? "1000"),
  S3_ENDPOINT: process.env.S3_ENDPOINT ?? "",
  S3_REGION: process.env.S3_REGION ?? "us-east-1",
  S3_BUCKET: process.env.S3_BUCKET ?? "",
  S3_ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID ?? "",
  S3_SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY ?? "",
  S3_PUBLIC_BASE_URL: process.env.S3_PUBLIC_BASE_URL ?? "",
  TIKTOK_CLIENT_KEY: process.env.TIKTOK_CLIENT_KEY ?? "",
  TIKTOK_CLIENT_SECRET: process.env.TIKTOK_CLIENT_SECRET ?? "",
  TIKTOK_RESEARCH_API_TOKEN: process.env.TIKTOK_RESEARCH_API_TOKEN ?? "",
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000",
};
